---
- name: update all packages
  apt:
    update_cache: yes
    name: "*"
    state: latest

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ percona.apt_list }}"

- name: install PyMySQL
  pip:
    name:
      - PyMySQL

- name: add Percona repo
  apt:
    deb: "{{ percona.repo }}"
  
- name: set Percona dist
  shell: |
    percona-release setup ps80

- name: install Percona 8.0
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ percona.packages }}"
  changed_when: true

- name:  run and enable Mysql
  systemd:
    name: "mysql"
    state: started
    enabled: yes

- name: check percona-release and mysql versions
  shell: |
    /usr/bin/percona-release show
    /usr/bin/mysql --version
  register: versions_check

- name: debug percona
  debug:
    msg: "{{ versions_check.stdout.split('\n') }}"