---
- name: Disable ufw Ubuntu
  include_tasks: ufw.yml
  tags: 
    - ufw

- name: Install Percona
  include_tasks: install_percona.yml
  tags: 
    - percona

- name: Configure Mysql Replica
  include_tasks: replica.yml
  tags: 
    - replica