---
percona:
  repo: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"
  apt_list:
    - ca-certificates
    - curl
    - lsb-release
    - mysql-client
    - git
    - python3-dev
    - python3-pip
    - gnupg2
    - lsb-release
    - htop
  packages:
    - percona-server-server
    - percona-server-client
    - percona-server-dbg
    - percona-xtrabackup-24
    - libperconaserverclient21-dev
    - libperconaserverclient21

ufw:
  service:
    state: "stopped"
    enabled: "no"

system_user: "{{ ansible_user }}"

mysql:
  cnf: /etc/mysql/mysql.conf.d/mysql.cnf

