#-----------------------------------------------------------------------
# AMI
#-----------------------------------------------------------------------
output "ubuntu_linux_latest_ami_id" {
  description = "The latest AMI ID for ubuntu 20.04"
  value       = data.aws_ami.ubuntu_linux_latest.id
}

output "ubuntu_linux_latest_ami_name" {
  description = "The latest AMI name for ubuntu 20.04"
  value       = data.aws_ami.ubuntu_linux_latest.name
}

#-----------------------------------------------------------------------
# SSH KEY
#-----------------------------------------------------------------------
output "ssh_key" {
  description = "ssh key generated by terraform"
  sensitive   = true
  value       = tls_private_key.ssh-key[0].private_key_pem
}

#-----------------------------------------------------------------------
# EC2
#-----------------------------------------------------------------------
output "Instances_info" {
  description = "Info about instances"
  value = {
    master_server = {
      "${lookup(aws_instance.master.tags_all, "Name")}" = {
        id         = aws_instance.master.id,
        public_ip  = aws_instance.master.public_ip,
        private_ip = aws_instance.master.private_ip,
        arn        = aws_instance.master.arn,
        dns        = aws_instance.master.public_dns
      }
    },
    slave_servers = {
      for k, slave in aws_instance.slave : k => {
        Name       = lookup(slave.tags_all, "Name")
        id         = slave.id,
        public_ip  = slave.public_ip,
        private_ip = slave.private_ip,
        arn        = slave.arn,
        dns        = slave.public_dns
      }
    }
  }
}

# output "Master_instances_ip" {
#   description = "Instances ip"
#   value       = replace(jsonencode(aws_instance.master.public_ip), "\"", "'")
# }

# output "Slave_instances_ip" {
#   description = "Instances ip"
#   value       = replace(jsonencode(aws_instance.slave[*].public_ip), "\"", "'")
# }
