#-----------------------------------------------------------------------
# Provider region
#-----------------------------------------------------------------------
variable "region" {
  description = "AWS Region for Genesis DevOps School"
  type        = string
  default     = "us-east-1"
}

#-----------------------------------------------------------------------
# Project name
#-----------------------------------------------------------------------
variable "project" {
  description = "The project name"
  type        = string
  default     = "Genesis"
}

#-----------------------------------------------------------------------
# The project Environment
#-----------------------------------------------------------------------
variable "env" {
  description = "The Environment for Genesis DevOps School"
  type        = string
  default     = "dev"
}

#-----------------------------------------------------------------------
# VPC
#-----------------------------------------------------------------------
variable "vpc_cidr" {
  description = "IPv4 CIDR for Genesis DevOps School"
  default     = "10.10.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "CIDRs for public subnets"
  type        = list(string)
  default = [
    "10.10.1.0/24",
    "10.10.2.0/24",
  ]
}

variable "privet_subnet_cidrs" {
  description = "CIDRs for privet subnets"
  type        = list(string)
  default = [
    "10.10.11.0/24",
    "10.10.12.0/24",
  ]
}

variable "enabled_dns_support" {
  type        = bool
  description = "enabling dns support"
  default     = true
}

variable "enabled_dns_hostnames" {
  type        = bool
  description = "enabling dns hostnames"
  default     = true
}

#-----------------------------------------------------------------------
# SSH
#-----------------------------------------------------------------------
variable "ssh_user_name" {
  description = "The user name for ssh"
  type        = string
  default     = ""
}

variable "ssh_key" {
  description = "Key-pair generated by Terraform"
  type        = map(any)
  default = {
    "install" = false
    "name"    = ""
  }
}

#-----------------------------------------------------------------------
# EC2
#-----------------------------------------------------------------------
variable "instance_type" {
  description = "Instance Type for application instance"
  type        = map(any)
  default = {
    "master" = "t2.micro"
    "slave"  = "t2.micro"
  }
}

variable "vm_slave_count" {
  description = "Count Slave instance"
  default     = 1
}

variable "host_name" {
  description = "Host names"
  type        = map(any)
  default = {
    "master" = "master"
    "slave"  = "replica"
  }
}

#-----------------------------------------------------------------------
# Security group
#-----------------------------------------------------------------------
variable "allow_port_list" {
  description = "List of Ports to open for all groups"
  type        = map(any)
  default = {
    "mysql" = ["3306"]
  }
}

variable "ssh_cidr" {
  description = "Private IP for ssh"
  type        = string
  default     = ""
}


#-----------------------------------------------------------------------
# Tags
#-----------------------------------------------------------------------
variable "common_tags" {
  description = "Common Tags to apply to all resources"
  type        = map(any)
  default = {
    Owner = ""
  }
}

#-----------------------------------------------------------------------
# Provisioner Ansible
#-----------------------------------------------------------------------
variable "ansible" {
  description = "Provisioning ansible for create app on the server"
  type        = bool
  default     = false
}