name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        required: true
        default: false
        description: Destroy
      TF_LOG:
        description: 'Terraform LOG'
        required: false
        default: 'INFO' 
        type: choice
        options:
        - INFO
        - DEBUG
        - TRACE

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    if: ${{ inputs.destroy }} == true
    env:
      TF_LOG: ${{ inputs.TF_LOG }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform/project_GENESIS

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: tf_init
        run: terraform init
        
      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true

      - name: Terraform destroy
        id: tf_destroy
        run: terraform destroy -auto-approve